#!/usr/bin/python

# x86-specific CPU types
CPU_8086 = "8086"
CPU_80286 = "80286"
CPU_80386 = "80386"
CPU_80387 = "80387"
CPU_80486 = "80486"
CPU_PENTIUM = "Pentium"
CPU_PENTIUMPRO = "Pentium Pro"
CPU_PENTIUM2 = "Pentium 2"
CPU_PENTIUM3 = "Pentium 3"
CPU_PENTIUM4 = "Pentium 4"
CPU_K6 = "K6"
CPU_K7 = "K7"
CPU_ATHLON = "Athlon"
# x86-specific ISA type
ISA_FPUMGT = "FPU/SIMD Management"
ISA_MMX = "MMX"
ISA_SSE1 = "SSE"
ISA_SSE2 = "SSE 2"
ISA_SSE3 = "SSE 3"
ISA_3DNOW = "3D Now"
# x86-specific insn types
TYPE_PUSHREGS = "pushregs"
TYPE_POPREGS = "popregs"
TYPE_PUSHFLAGS = "pushflags"
TYPE_POPFLAGS = "popflags"
TYPE_STRCMP = "strcmp"
TYPE_STRLOAD = "load str"
TYPE_STRMOV = "move str"
TYPE_STRSTORE = "store str"
TYPE_TRANSLATE = "xlat"
TYPE_ROL = "rol"
TYPE_ROR = "ror"
TYPE_FLAGSET = "fset"
TYPE_FLAGCLEAR = "fclear"
TYPE_FLAGTOG = "ftog"
TYPE_LDPI = "ldpi fp"
TYPE_LDZ = "ldz fp"
TYPE_BCDCONV = "conv bcd"
TYPE_SZCONV = "conv size"
# names of constants
CONST_PI = "pi"
CONST_ZERO = "zero"
# names of eflags
EFLAG_CARRY = "cf"
EFLAG_ZERO = "zf"
EFLAG_OFLOW = "of"
EFLAG_DIR = "df"
EFLAG_SIGN = "sf"
EFLAG_PARITY = "pf"
EFLAG_AUX = "af"
EFLAG_TRAP = "tf"
EFLAG_INT = "if"
# names of segment registers
SEGREG_ES = "es"
SEGREG_CS = "cs"
SEGREG_SS = "ss"
SEGREG_DS = "ds"
SEGREG_FS = "fs"
SEGREG_GS = "gs"
